name: Vault Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  push-to-registry:
    name: Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        id: checkout
        uses: actions/checkout@v2
      - name: get latest tag
        id: latest_tag
        run: |
          echo ::set-output name=tags::${GITHUB_REF#refs/*/}
      - name: Push Docker Image 
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}
          repository: provide/vault
          tags: "${{ steps.latest_tag.outputs.tags}}, latest"
